# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Please check for the latest stable version of ruff-pre-commit
    # from https://github.com/astral-sh/ruff-pre-commit/releases
    # and update the 'rev' value accordingly.
    rev: "v0.12.12" # As of June 2024, v0.4.4 is a recent version
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --unsafe-fixes] # --fix attempts to fix issues
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/fpgmaas/deptry
    rev: "0.23.1"
    hooks:
      - id: deptry
        # Pass args if you need to ignore specific violations, e.g.
        # args: ["--ignore", "DEP002"]

  - repo: https://github.com/python-poetry/poetry
    rev: "2.1.3"
    hooks:
      - id: poetry-check
      - id: poetry-lock

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: "1.9.0"
    hooks:
      - id: poetry-export
        args:
          [
            "--without-hashes",
            "-f",
            "requirements.txt",
            "-o",
            "requirements.txt",
          ]
