site_name: Aurite Agents Documentation
site_description: Documentation for Aurite Agents, a framework for building AI agents.
site_author: Aurite AI
site_url: https://aurite-ai.github.io/aurite-agents
repo_url: https://github.com/Aurite-ai/aurite-agents
repo_name: Aurite-ai/aurite-agents
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/aurite_logo.png
  favicon: images/aurite_logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  # - mkdocs-jupyter
  - search

extra_css:
  - assets/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aurite-ai
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/aurite-agents/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - "Home": "index.md"
  - "Getting Started":
      - "Quick Start": "getting-started/quick_start.md"
      - "Installation":
          - "Package Installation": "getting-started/installation_guides/package_installation_guide.md"
          - "Repository Installation": "getting-started/installation_guides/repository_installation_guide.md"
      - "Tutorials":
          - "Overview": "getting-started/tutorials/Tutorials_Overview.md"
          - "01: Introducing Aurite Agents": "getting-started/tutorials/01_Introducing_Aurite_Agents.ipynb"
          - "02: Agents and Tools": "getting-started/tutorials/02_Agents_and_Tools.ipynb"
          - "03: Agent Challenge": "getting-started/tutorials/03_Agent_Challenge.ipynb"
          - "04: Agent Challenge Solutions": "getting-started/tutorials/04_Agent_Challenge_Solutions.ipynb"
          - "05: LLMs, Schemas, and Workflows": "getting-started/tutorials/05_LLMs_Schemas_and_Workflows.ipynb"
          - "06: Building Your Own MCP Server": "getting-started/tutorials/06_Building_Your_Own_MCP_Server.md"
          - "07: Understanding Projects": "getting-started/tutorials/07_Understanding_Projects.md"
  - "Usage":
      - "CLI Reference": "usage/cli_reference.md"
      - "API Reference": "usage/api_reference.md"
      - "TUI Guide": "usage/tui_guide.md"
  - "Configurations":
      - "Projects and Workspaces": "config/projects_and_workspaces.md"
      - "Components":
          - "Agent": "config/agent.md"
          - "LLM": "config/llm.md"
          - "Linear Workflow": "config/linear_workflow.md"
          - "Custom Workflow": "config/custom_workflow.md"
          - "MCP Server": "config/mcp_server.md"
  - "Architecture":
      - "Overview": "architecture/overview.md"
      - "Design":
          - "Aurite Engine": "architecture/design/aurite_engine_design.md"
          - "Config Manager": "architecture/design/config_manager_design.md"
          - "MCP Host": "architecture/design/mcp_host_design.md"
      - "Flow":
          - "Aurite Engine Flow": "architecture/flow/aurite_engine_execution_flow.md"
          - "Config Index Building": "architecture/flow/config_index_building_flow.md"
          - "MCP Server Registration": "architecture/flow/mcp_server_registration_flow.md"
          - "Session Management": "architecture/flow/session_management_flow.md"

exclude_docs: |
  internal/
  /internal/*
  copilot_guides/
