[project]
name = "aurite-mcp"
version = "0.1.0"
description = "Aurite MCP implementation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=0.1.0",
    "httpx>=0.25.0",
    "anyio>=3.8.0",
    "sqlalchemy>=2.0.0",
]
