test_type: custom_workflow
name: ExampleCustomWorkflow
user_input:
  city: San Francisco
iterations: 1
retry: false
max_retries: 0
edit_prompt: false
editor_model: gemini
evaluation_type: default
testing_prompt: Your job is to evaluate the work done by the Weather Workflow. Ensure that it gives the weather for the city specified in the user input.