test_type: agent
name: Documentation Chat Agent
user_input:
  - What is the difference between a simple and custom workflow?
  - Give me a quick guide for how to set up a new agent
  - Define 'host' for this project
iterations: 1
retry: false
max_retries: 0
edit_prompt: false
editor_model: gemini
evaluation_type: default
testing_prompt: Your job is to evaluate the work done by the Documentation Chat Agent. Ensure that it gives a suitable answer to the question asked by the user, including references to specific documentation files by name.
expected_tools:
  - name: search
    ge: 1