test_type: agent
name: Mapping Agent
user_input: What is the distance between Alice and Bob's houses?
iterations: 1
retry: false
max_retries: 0
edit_prompt: false
editor_model: gemini
evaluation_type: default
testing_prompt: Your job is to evaluate the work done by the Mapping Agent. Ensure that it gives a suitable answer to the question asked by the user, including addresses and units if applicable.
expected_tools:
  - name: get_address
    eq: 2
  - name: calculate_distance
    eq: 1
analysis: false