test_type: workflow
name: main
user_input: What is the current weather in San Francisco?
iterations: 1
retry: false
max_retries: 0
edit_prompt: false
editor_model: gemini
evaluation_type: default
testing_prompt: Your job is to evaluate the work done by the Weather Workflow. Ensure that it gives a suitable answer to the question asked by the user, including temperature and weather conditions if applicable.