test_type: agent
name: OpenAI Weather Agent
user_input: What is the weather in London, England?
iterations: 1
retry: false
max_retries: 0
edit_prompt: false
editor_model: gemini
evaluation_type: default
testing_prompt: Your job is to evaluate the work done by the Weather Agent. Ensure that it gives a suitable answer to the question asked by the user. It should specify temperature and humidity.
expected_tools:
  - name: weather_lookup
    eq: 1
analysis: true