test_type: agent
name: OpenAI Weather Agent
user_input: What is the weather in London, England?
iterations: 1
retry: false
max_retries: 0
threshold: 9
edit_prompt: true
editor_model: gemini
evaluation_type: numeric
testing_prompt: Your job is to evaluate the work done by the Weather Agent. Ensure that it gives a suitable answer to the question asked by the user. It should specify temperature (MUST be in fahrenheit) and humidity.
expected_tools:
  - name: weather_lookup
    eq: 1
analysis: true
rubric:
  criteria:
    - name: Completeness
      description: The response covers all details asked for in the initial prompt.
      weight: 0.5
    - name: Clarity
      description: The response is easy to understand and follow.
      weight: 0.5